### ISSUE TITLE
compiler errors for ndn-cxx after 0.5.0

### ISSUE THREAD

**Issue by jefft0** [named-data/ndn-group-encrypt#2]
With ndn-cxx version 0.5.0 (October 2016), I am able to build ndn-group-encrypt. But with the latest ndn-cxx `./waf` give this error:

    ../src/producer.cpp:103:16: error: no matching constructor for initialization of 'AesKeyParams'

Maybe this due to the new ndn-cxx security library? Does ndn-group-encrypt compile for you?

**Comment by cawka** [comment]
This is a small bug in the library that was introduced recently (https://redmine.named-data.net/issues/3989).  Should work after it is fixed.

**Comment by Pesa** [comment]
Fixed a long time ago.
